In [45]:
import numpy as np

In [46]:
limit = 10  # range of integers to be generated
tolerance = 1e-06   # teolrance of error

# Generate a Random Invertible Matrix of integers
In mathematics, a square matrix is said to be diagonally dominant if, for every row of the matrix, the magnitude of the diagonal entry in a row is larger than or equal to the sum of the magnitudes of all the other (non-diagonal) entries in that row. A diagonally dominant matrix is invertible.

In the following function, the diagonal entry of each row is replaced by the sum of that row. So that entry is always greater than all ither entries of the row

In [47]:
def generate_invertible_matrix(n):
    matrix = np.random.randint(limit, size = (n, n))
    row_sums = np.sum(np.abs(matrix), axis = 1)
    np.fill_diagonal(matrix, row_sums)
    return matrix

In [48]:
M = generate_invertible_matrix(3)
M

array([[14,  5,  2],
       [ 8, 17,  6],
       [ 3,  7, 10]])

In [49]:
eigen_values, eigen_vectors = np.linalg.eig(M)
print(f'Eigen Values {eigen_values}')
print(f'Eigen Vectors {eigen_vectors}')

Eigen Values [24.97183527 10.13025946  5.89790527]
Eigen Vectors [[-0.43686342 -0.72975377  0.12958187]
 [-0.77810447  0.3239556  -0.54208572]
 [-0.45133555  0.60208987  0.83027201]]


In [50]:
def check_reconstruction(M, eigen_values, eigen_vectors):
    lambda_matrix = np.diag(eigen_values)
    inv_eigenvector = np.linalg.inv(eigen_vectors)
    reconstructed_matrix = np.matmul(lambda_matrix, inv_eigenvector)
    reconstructed_matrix = np.matmul(eigen_vectors, reconstructed_matrix)
    
    print(f'Given Matrix {M}')
    print(f'Reconstructed Matrix {reconstructed_matrix}')
    print(f'Is Reconstruction Perfect? : {np.allclose(M, reconstructed_matrix, tolerance)}')

In [51]:
check_reconstruction(M, eigen_values, eigen_vectors)

Given Matrix [[14  5  2]
 [ 8 17  6]
 [ 3  7 10]]
Reconstructed Matrix [[14.  5.  2.]
 [ 8. 17.  6.]
 [ 3.  7. 10.]]
Is Reconstruction Perfect? : True
